#!/bin/bash

echo "🧪 Manual Extension Test Guide"
echo "=============================="
echo ""
echo "Since Puppeteer has issues with Manifest V3 extensions,"
echo "follow these steps to manually test the extension:"
echo ""
echo "1️⃣  LOAD EXTENSION IN CHROME"
echo "   • Open Chrome/Edge"
echo "   • Go to: chrome://extensions/"
echo "   • Enable 'Developer mode' (top right)"
echo "   • Click 'Load unpacked'"
echo "   • Select this directory: $(pwd)"
echo ""
echo "2️⃣  VERIFY EXTENSION LOADS"
echo "   • Check for Web Summary AI icon in toolbar"
echo "   • No errors should appear on extensions page"
echo ""
echo "3️⃣  TEST ON A WEB PAGE"
echo "   • Open a new tab"
echo "   • Visit any article page (e.g., Wikipedia, Medium)"
echo "   • Look for floating button (bottom-right corner)"
echo ""
echo "4️⃣  TEST FUNCTIONALITY"
echo "   • Click the floating button"
echo "   • Summary panel should appear"
echo "   • Prompt should be generated"
echo "   • Click extension icon to open popup"
echo ""
echo "5️⃣  PRIVACY TEST"
echo "   • Open DevTools (F12)"
echo "   • Go to Network tab"
echo "   • Clear network log"
echo "   • Click floating button to generate summary"
echo "   • VERIFY: No external API calls made"
echo "   • Should only see chrome-extension:// URLs"
echo ""
echo "6️⃣  YOUTUBE TEST"
echo "   • Visit any YouTube video"
echo "   • Click floating button"
echo "   • Should extract transcript if available"
echo ""
echo "7️⃣  SETTINGS TEST"
echo "   • Click extension icon"
echo "   • Click 'Settings' or right-click extension → Options"
echo "   • Verify all settings load"
echo "   • Change theme/colors"
echo "   • Settings should persist"
echo ""
echo "✅ If all tests pass, extension is working correctly!"
echo ""
echo "Press Ctrl+C to exit or wait for automated check..."
echo ""

# Try to detect if Chrome is available
if command -v open &> /dev/null; then
    read -p "🚀 Open Chrome extensions page now? (y/n) " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        open -a "Google Chrome" "chrome://extensions/"
        echo "✅ Opened Chrome extensions page"
        echo "💡 Now load this directory as an unpacked extension"
    fi
fi
